"""init

Revision ID: c9fae560fdab
Revises: 
Create Date: 2026-06-29 14:33:40.314531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fae560fdab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('homepage_url', sa.String(length=512), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=True),
    sa.Column('github_stars', sa.Integer(), nullable=False),
    sa.Column('github_forks', sa.Integer(), nullable=False),
    sa.Column('github_open_issues', sa.Integer(), nullable=False),
    sa.Column('github_license', sa.String(length=100), nullable=True),
    sa.Column('github_language', sa.String(length=50), nullable=True),
    sa.Column('github_topics', sa.JSON(), nullable=True),
    sa.Column('github_description', sa.Text(), nullable=True),
    sa.Column('github_updated_at', sa.DateTime(), nullable=True),
    sa.Column('github_created_at', sa.DateTime(), nullable=True),
    sa.Column('biotools_id', sa.String(length=100), nullable=True),
    sa.Column('publication_doi', sa.String(length=255), nullable=True),
    sa.Column('publication_title', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_url'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_tools_created_at'), 'tools', ['created_at'], unique=False)
    op.create_index(op.f('ix_tools_github_language'), 'tools', ['github_language'], unique=False)
    op.create_index(op.f('ix_tools_github_stars'), 'tools', ['github_stars'], unique=False)
    op.create_index(op.f('ix_tools_github_updated_at'), 'tools', ['github_updated_at'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=False)
    op.create_table('tool_categories',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('tool_id', 'category_id')
    )
    op.create_table('tool_stats_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'snapshot_date', name='uq_tool_snapshot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_stats_history')
    op.drop_table('tool_categories')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_index(op.f('ix_tools_github_updated_at'), table_name='tools')
    op.drop_index(op.f('ix_tools_github_stars'), table_name='tools')
    op.drop_index(op.f('ix_tools_github_language'), table_name='tools')
    op.drop_index(op.f('ix_tools_created_at'), table_name='tools')
    op.drop_table('tools')
    # ### end Alembic commands ###
